---
# prettier-plugin-ini
iniSpaceAroundEquals: true

# prettier-plugin-sql
language: postgresql
keywordCase: upper

overrides:
  - files: .editorconfig
    options:
      parser: ini

  - files: .gitlint
    options:
      parser: ini
