---
creation_rules:
  - path_regex: etc/local/.*
    age: age198r3u086e4fury59m864adjyh5y0lw7keprttej4gkur797hyvmqku56hh

  - path_regex: etc/test/.*
    age: age198r3u086e4fury59m864adjyh5y0lw7keprttej4gkur797hyvmqku56hh
