---
extends: default

ignore: |
  secrets.yaml

rules:
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  line-length:
    max: 120
  new-line-at-end-of-file: enable
  trailing-spaces: false
