---
exclude:
  - "**/secrets.yaml"

formatter:
  type: basic
  # Trying to get this sourced from .editorconfig.
  # See: <https://github.com/google/yamlfmt/issues/61>
  indent: 2
  include_document_start: true
  retain_line_breaks: true
