name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write # to create releases
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # pin@v2.4.1

      # Needed to expose GHA env vars to buildkit (since we're manually invoking)
      # See: https://docs.docker.com/build/cache/backends/gha/#authentication
      # cspell: words ghaction
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@747e98cd97bb9cfed8fe0165c821a83139bfdd67 # pin@v2.1.0

      - name: Build
        run: make docker-build

      - name: Inspect
        run: make docker-inspect

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: make release
